"""Thin wasmmod-cdn HTTP client (``pymergetic-wasmmod-cdn-client``)."""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

from pymergetic.wasmmod.cdn_client.client import ArtifactDownload, CdnClient, ClientError
from pymergetic.wasmmod.cdn_client.config import (
    TOKEN_SOURCE_API_KEY,
    TOKEN_SOURCE_OIDC,
    ClientConfig,
    TokenSource,
    clear_token,
    config_dir,
    config_path,
    load_config,
    save_config,
    token_source,
)
from pymergetic.wasmmod.cdn_client.contents import (
    ArtifactContents,
    ArtifactContentsSummary,
    ContainerSectionInfo,
    DepInfo,
    DisasmLineInfo,
    EmbeddedFileView,
    ImportInfo,
    LocationInfo,
    PackageContents,
    PackExportInfo,
    PackFileInfo,
    PackSectionInfo,
    SigCertInfo,
    SigSectionInfo,
    SourceFileInfo,
    SourceSectionInfo,
    SymbolInfo,
    ensure_zlib_artifacts,
    extract_container_section,
    extract_embedded_bytes,
    extract_embedded_file,
    inspect_artifact,
    inspect_upload,
    list_container_sections,
    list_pack_symbols,
    merge_contents,
    pack_addr2line,
    pack_disasm,
    pack_has_dwarf,
    pack_locations,
    pack_mpy_disasm,
    unwrap_mpzl,
    wrap_mpzl,
)
from pymergetic.wasmmod.cdn_client.errors import (
    die,
    die_client,
    format_client_error,
    format_error,
    hints_for_client_error,
    invoke,
    report,
    report_client_error,
)
from pymergetic.wasmmod.cdn_client.format import hexdump, human_size
from pymergetic.wasmmod.cdn_client.verify import (
    RequireSignedMode,
    VerifyResult,
    enforce_signed_policy,
    verify_artifact,
)
from pymergetic.wasmmod.cdn_client.trust import (
    FP_LEN,
    MPTB_MAGIC,
    MPTB_TYPE_TRUST,
    MPTB_VER,
    MptbBundle,
    MptbError,
    SubcaPolicy,
    parse_mptb,
    subca_of_chain,
)


def resolve_version() -> str:
    try:
        return version("pymergetic-wasmmod-cdn-client")
    except PackageNotFoundError:
        return "0.0.0+unknown"


__version__ = resolve_version()

__all__ = [
    "TOKEN_SOURCE_API_KEY",
    "TOKEN_SOURCE_OIDC",
    "ArtifactContents",
    "ArtifactContentsSummary",
    "ArtifactDownload",
    "CdnClient",
    "ClientConfig",
    "ClientError",
    "ContainerSectionInfo",
    "DepInfo",
    "DisasmLineInfo",
    "EmbeddedFileView",
    "ImportInfo",
    "LocationInfo",
    "MPTB_MAGIC",
    "MPTB_TYPE_TRUST",
    "MPTB_VER",
    "MptbBundle",
    "MptbError",
    "PackExportInfo",
    "PackFileInfo",
    "PackageContents",
    "PackSectionInfo",
    "RequireSignedMode",
    "SigCertInfo",
    "SigSectionInfo",
    "SourceFileInfo",
    "SourceSectionInfo",
    "SubcaPolicy",
    "SymbolInfo",
    "TokenSource",
    "VerifyResult",
    "__version__",
    "clear_token",
    "config_dir",
    "config_path",
    "die",
    "die_client",
    "enforce_signed_policy",
    "ensure_zlib_artifacts",
    "extract_container_section",
    "extract_embedded_bytes",
    "extract_embedded_file",
    "format_client_error",
    "format_error",
    "hexdump",
    "hints_for_client_error",
    "human_size",
    "inspect_artifact",
    "inspect_upload",
    "invoke",
    "list_container_sections",
    "list_pack_symbols",
    "load_config",
    "merge_contents",
    "pack_addr2line",
    "pack_disasm",
    "pack_has_dwarf",
    "pack_locations",
    "pack_mpy_disasm",
    "parse_mptb",
    "report",
    "report_client_error",
    "save_config",
    "subca_of_chain",
    "token_source",
    "unwrap_mpzl",
    "verify_artifact",
    "wrap_mpzl",
]
