"""Inspect wasmmod .wasm / .aot / .elf (and MPZL .zlib) for CDN index ``contents``.

Shared by metal-cdn (on upload) and host tools. Inventory / metadata only —
file bodies are not embedded. Models are Pydantic so index JSON stays typed.

Split into submodules; this package re-exports the stable public API.
"""

from __future__ import annotations

from pymergetic.metal.cdn_client.contents.const import (
    DEPS_MAGIC,
    DEPS_SECTION,
    IMPORTS_MAGIC,
    IMPORTS_SECTION,
    KIND_NAMES,
    MPWS_MAGIC,
    MPWS_VER,
    MPZL_MAGIC,
    PACK_MAGIC,
    PACK_SECTION,
    SECTION_RAW_LIMIT_CAP,
    SIG_AUTO,
    SIG_SECTION,
    SOURCE_MAGIC,
    SOURCE_SECTION,
)
from pymergetic.metal.cdn_client.contents.extract import (
    extract_embedded_bytes,
    extract_embedded_file,
)
from pymergetic.metal.cdn_client.contents.host_ops import (
    list_pack_symbols,
    pack_addr2line,
    pack_disasm,
    pack_has_dwarf,
    pack_locations,
    pack_mpy_disasm,
)
from pymergetic.metal.cdn_client.contents.inventory import (
    inspect_artifact,
    inspect_upload,
    merge_contents,
)
from pymergetic.metal.cdn_client.contents.models import (
    ArtifactBinaryKind,
    ArtifactContents,
    ArtifactContentsSummary,
    ArtifactEnvelope,
    ContainerSectionInfo,
    DepInfo,
    DisasmLineInfo,
    EmbeddedFileView,
    ImportInfo,
    LocationInfo,
    PackageContents,
    PackExportInfo,
    PackFileInfo,
    PackSectionInfo,
    SigCertInfo,
    SigSectionInfo,
    SourceFileInfo,
    SourceSectionInfo,
    SymbolInfo,
)
from pymergetic.metal.cdn_client.contents.mpzl import (
    ensure_zlib_artifacts,
    install_unwrap_override,
    unwrap_mpzl,
    unwrap_mpzl_raw,
    wrap_mpzl,
)
from pymergetic.metal.cdn_client.contents.parse import (
    parse_deps_payload,
    parse_imports_payload,
    parse_pack_payload,
    parse_sig_payload,
    parse_source_payload,
    split_der_certs,
    without_sig_section,
)
from pymergetic.metal.cdn_client.contents.sections import (
    describe_binder_sig,
    extract_container_section,
    extract_custom_section,
    extract_custom_section_aot,
    extract_custom_section_elf,
    extract_custom_section_wasm,
    has_section,
    list_container_sections,
    slice_bytes,
    wasm_func_export_typesigs,
)

__all__ = [
    "DEPS_MAGIC",
    "DEPS_SECTION",
    "IMPORTS_MAGIC",
    "IMPORTS_SECTION",
    "KIND_NAMES",
    "MPWS_MAGIC",
    "MPWS_VER",
    "MPZL_MAGIC",
    "PACK_MAGIC",
    "PACK_SECTION",
    "SECTION_RAW_LIMIT_CAP",
    "SIG_AUTO",
    "SIG_SECTION",
    "SOURCE_MAGIC",
    "SOURCE_SECTION",
    "ArtifactBinaryKind",
    "ArtifactContents",
    "ArtifactContentsSummary",
    "ArtifactEnvelope",
    "ContainerSectionInfo",
    "DepInfo",
    "DisasmLineInfo",
    "EmbeddedFileView",
    "ImportInfo",
    "LocationInfo",
    "PackExportInfo",
    "PackFileInfo",
    "PackSectionInfo",
    "PackageContents",
    "SigCertInfo",
    "SigSectionInfo",
    "SourceFileInfo",
    "SourceSectionInfo",
    "SymbolInfo",
    "describe_binder_sig",
    "ensure_zlib_artifacts",
    "extract_container_section",
    "extract_custom_section",
    "extract_custom_section_aot",
    "extract_custom_section_elf",
    "extract_custom_section_wasm",
    "extract_embedded_bytes",
    "extract_embedded_file",
    "has_section",
    "inspect_artifact",
    "inspect_upload",
    "list_container_sections",
    "list_pack_symbols",
    "merge_contents",
    "pack_addr2line",
    "pack_disasm",
    "pack_has_dwarf",
    "pack_locations",
    "pack_mpy_disasm",
    "parse_deps_payload",
    "parse_imports_payload",
    "parse_pack_payload",
    "parse_sig_payload",
    "parse_source_payload",
    "slice_bytes",
    "split_der_certs",
    "install_unwrap_override",
    "unwrap_mpzl",
    "unwrap_mpzl_raw",
    "wasm_func_export_typesigs",
    "without_sig_section",
    "wrap_mpzl",
]
