from __future__ import annotations

def is_elf64_le(buf: bytes) -> bool: ...
def find_section(buf: bytes, name: str) -> bytes | None: ...
def append_section(buf: bytes, name: str, payload: bytes) -> bytes: ...
