# Autogenerated file
def render(d):
    yield """<section class=\"docs-hero\">
  <p class=\"eyebrow\">OpenAPI</p>
  <h1>API</h1>
  <p class=\"lede\">Interactive schema for publish, packages, ACL, and artifacts — same shell as browse.</p>
</section>
<div id=\"swagger-ui\" class=\"swagger-host\"></div>
<script src=\"https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js\" crossorigin></script>
<script>
  window.ui = SwaggerUIBundle("""
    yield """{
    url: \""""
    yield str(d.openapi_url)
    yield """\",
    dom_id: \"#swagger-ui\",
    deepLinking: true,
    presets: [SwaggerUIBundle.presets.apis],
    layout: \"BaseLayout\",
    tryItOutEnabled: true,
    persistAuthorization: true,
    syntaxHighlight: """
    yield """{ activated: true, theme: \"monokai\" },
    docExpansion: \"list\",
    defaultModelsExpandDepth: 1,
  });
</script>
"""
