# Autogenerated file
def render(d):
    yield """<section class=\"hero\">
  <p class=\"eyebrow\">package</p>
  """
    if d.fed_origin == 'remote':
        yield """  <p class=\"fed-banner\" role=\"status\">
    <span class=\"pill pill-remote\">remote</span>
    Federated via """
        yield str(d.fed_peer_label)
        yield """.
    """
        if d.fed_peer_browse_url:
            yield """    <a href=\""""
            yield str(d.fed_peer_browse_url)
            yield """\" rel=\"noopener\" target=\"_blank\">Visit on remote CDN</a>
    """
        yield """  </p>
  """
    yield """  """
    if d.package_role in ('host', 'kernel', 'arch', 'engine'):
        yield """  <p class=\"fed-banner\" role=\"status\">
    <span class=\"pill pill-"""
        yield str(d.package_role)
        yield """\">"""
        yield str(d.package_role)
        yield """</span>
    """
        if d.is_unix_seat:
            yield """    Unix host seat — curl the lead <code>.elf</code>, <code>chmod +x</code>, run. Inspect + download; Play disabled.
    """
        elif d.package_role == 'engine':
            yield """    CDN engine — browser host that loads guests / packs. Inspect + download; Play disabled.
    """
        elif d.package_role == 'arch' and d.name.endswith('.wasm'):
            yield """    Architecture seat (browser) — CDN UI <code>mp</code> engine loads these artifacts. Inspect + download; Play disabled.
    """
        elif d.package_role == 'arch':
            yield """    Architecture image — freestanding firmware; Inspect + download; iPXE loads these URLs. Play disabled.
    """
        else:
            yield """    Platform """
            yield str(d.package_role)
            yield """ — Inspect only; Play/Try guest-load is disabled.
    """
        yield """  </p>
  """
    yield """  <div class=\"hero-title-row\">
    <h1>"""
    yield str(d.name)
    if d.package_role in ('host', 'kernel', 'arch', 'engine'):
        yield """ <span class=\"pill pill-"""
        yield str(d.package_role)
        yield """\">"""
        yield str(d.package_role)
        yield """</span>"""
    yield """</h1>
    """
    if d.package_versions:
        yield """    <label class=\"pkg-ver-picker\">
      <span class=\"muted\">channel</span>
      <select id=\"pkg-version-select\" aria-label=\"Package version\">
        """
        for v in d.package_versions:
            yield """        <option
          value=\""""
            yield str(v.channel)
            yield """\"
          data-href=\""""
            yield str(v.href)
            yield """\"
          """
            if v.is_current:
                yield """selected"""
            yield """        >"""
            yield str(v.label)
            yield """</option>
        """
        yield """      </select>
    </label>
    """
    yield """  </div>
  <p class=\"lede\">
    """
    if d.channel == "lead":
        yield """    lead · """
        yield str(d.entry.version)
        yield """
    """
    else:
        yield """    pin """
        yield str(d.channel)
        yield """ · """
        yield str(d.entry.version)
        yield """
    """
    yield """    """
    if d.entry.license:
        yield """ · """
        yield str(d.entry.license)
    yield """    """
    if d.package_versions_len > 1:
        yield """    · <a href=\"#history\">"""
        yield str(d.package_versions_len)
        yield """ channels</a>
    """
    yield """  </p>
  """
    if d.entry.description:
        yield """  <p>"""
        yield str(d.entry.description)
        yield """</p>
  """
    yield """  """
    if d.entry.homepage:
        yield """  <p><a href=\""""
        yield str(d.entry.homepage)
        yield """\" rel=\"noopener\">"""
        yield str(d.entry.homepage)
        yield """</a></p>
  """
    yield """  """
    if d.entry.yanked:
        yield """  <p class=\"muted\">Yanked"""
        if d.entry.yank_reason:
            yield """: """
            yield str(d.entry.yank_reason)
        yield """</p>
  """
    yield """  """
    if d.entry.deprecated:
        yield """  <p class=\"muted\">Deprecated</p>
  """
    yield """  """
    if d.entry.successor:
        yield """  <p>Successor: <code>"""
        yield str(d.entry.successor)
        yield """</code></p>
  """
    yield """</section>

<section class=\"about\">
  <h2>About</h2>
  <dl class=\"meta-grid\">
    <dt>Package</dt><dd><code>"""
    yield str(d.name)
    yield """</code></dd>
    <dt>Version</dt>
    <dd>
      <a href=\"#history\"><code>"""
    yield str(d.entry.version)
    yield """</code></a>
      """
    if d.channel == "lead":
        yield """      <span class=\"pill pill-lead\">lead</span>
      """
    yield """    </dd>
    <dt>Channel</dt>
    <dd><a href=\""""
    yield str(d.channel_href)
    yield """\"><code>"""
    yield str(d.channel)
    yield """</code></a></dd>
    """
    if d.author_href:
        yield """    <dt>Author</dt>
    <dd><a href=\""""
        yield str(d.author_href)
        yield """\">"""
        yield str(d.entry.maintainer_email)
        yield """</a></dd>
    """
    yield """    """
    if d.entry.license:
        yield """    <dt>License</dt><dd>"""
        yield str(d.entry.license)
        yield """</dd>
    """
    yield """    """
    if d.entry.homepage:
        yield """    <dt>Homepage</dt><dd><a href=\""""
        yield str(d.entry.homepage)
        yield """\" rel=\"noopener\">"""
        yield str(d.entry.homepage)
        yield """</a></dd>
    """
    yield """    """
    if d.entry.aot_version:
        yield """    <dt>AOT</dt><dd>"""
        yield str(d.entry.aot_version)
        yield """</dd>
    """
    yield """  </dl>
</section>

"""
    if d.deps_links:
        yield """<section>
  <h2>Dependencies</h2>
  <p class=\"muted\">Packages this one needs (<code>[deps]</code> / MPWD). Green = exact version published; red = missing/yanked.</p>
  <ul class=\"pkg-list\">
    """
        for dep in d.deps_links:
            yield """    <li>
      <a class=\"dep-chip """
            if dep.ok:
                yield """dep-chip-ok"""
            else:
                yield """dep-chip-bad"""
            yield """\"
         href=\""""
            yield str(dep.href)
            yield """\"><code>"""
            yield str(dep.name)
            yield """</code></a>
      <a class=\"ver\" href=\""""
            yield str(dep.ver_href)
            yield """\">"""
            yield str(dep.ver)
            yield """</a>
      """
            if not dep.ok:
                yield """<span class=\"pill pill-warn\">unfit</span>"""
            yield """    </li>
    """
        yield """  </ul>
</section>
"""
    if d.needed_links:
        yield """<section>
  <h2>Needed by</h2>
  <p class=\"muted\">Known published packages that list this one in their <code>[deps]</code>.</p>
  <ul class=\"pkg-list\">
    """
        for dep in d.needed_links:
            yield """    <li>
      <a class=\"dep-chip"""
            yield str(dep.cls)
            yield """\" href=\""""
            yield str(dep.href)
            yield """\"><code>"""
            yield str(dep.name)
            yield """</code></a>
    </li>
    """
        yield """  </ul>
</section>
"""
    if d.package_versions:
        yield """<section id=\"history\">
  <h2>Version history</h2>
  <p class=\"muted\">Lead channel plus immutable pins. Click a row to open that publish.</p>
  <div class=\"pkg-table-wrap\">
    <table class=\"pkg-table pkg-history\" id=\"pkg-history\"
           data-show=\"3\" data-total=\""""
        yield str(d.package_versions_len)
        yield """\">
      <thead>
        <tr>
          <th scope=\"col\">Channel</th>
          <th scope=\"col\">Version</th>
          <th scope=\"col\">Arts</th>
        </tr>
      </thead>
      <tbody>
        """
        for v in d.package_versions:
            yield """        <tr class=\""""
            if v.is_current:
                yield """is-current"""
            if v.folded:
                yield """ history-fold"""
            yield """\"
            """
            if v.folded:
                yield """hidden"""
            yield """>
          <td>
            <a href=\""""
            yield str(v.href)
            yield """\">
              """
            if v.channel == 'lead':
                yield """              <span class=\"pill pill-lead\">lead</span>
              """
            else:
                yield """              <code>"""
                yield str(v.channel)
                yield """</code>
              """
            yield """            </a>
          </td>
          <td><a class=\"ver\" href=\""""
            yield str(v.href)
            yield """\">"""
            yield str(v.version)
            yield """</a></td>
          <td class=\"mono\">"""
            yield str(v.artifact_count)
            yield """</td>
        </tr>
        """
        yield """      </tbody>
    </table>
  </div>
  """
        if d.version_fold_count > 0:
            yield """  <p class=\"history-more-wrap\">
    <button type=\"button\" class=\"history-more-btn\" id=\"history-more-btn\"
            aria-expanded=\"false\" aria-controls=\"pkg-history\">
      Show """
            yield str(d.version_fold_count)
            yield """ older
    </button>
  </p>
  """
        yield """</section>
<script>
(() => """
        yield """{
  const sel = document.getElementById(\"pkg-version-select\");
  if (sel) """
        yield """{
    sel.addEventListener(\"change\", () => """
        yield """{
      const opt = sel.selectedOptions[0];
      if (opt && opt.dataset.href) window.location.href = opt.dataset.href;
    });
  }
  const btn = document.getElementById(\"history-more-btn\");
  const table = document.getElementById(\"pkg-history\");
  if (!btn || !table) return;
  const folded = () => Array.from(table.querySelectorAll(\"tr.history-fold\"));
  folded().forEach((tr) => """
        yield """{
    if (tr.classList.contains(\"is-current\")) tr.hidden = false;
  });
  const rest = () => folded().filter((tr) => tr.hidden).length;
  const sync = (open) => """
        yield """{
    folded().forEach((tr) => """
        yield """{
      if (!open && tr.classList.contains(\"is-current\")) return;
      tr.hidden = !open;
    });
    btn.setAttribute(\"aria-expanded\", open ? \"true\" : \"false\");
    const n = rest();
    btn.textContent = open ? \"Show fewer\" : (\"Show \" + n + \" older\");
    btn.hidden = !open && n === 0;
  };
  btn.addEventListener(\"click\", () => """
        yield """{
    sync(btn.getAttribute(\"aria-expanded\") !== \"true\");
  });
  sync(false);
})();
</script>
"""
    if d.is_unix_seat and d.channel == "lead":
        yield """<section>
  <h2>Run (curl)</h2>
  <p class=\"muted\">
    Linux userspace seat — download the lead ELF and execute it (banner + REPL).
    Inspect / download also in <a href=\"#artifact-list\">Artifacts</a>.
  </p>
  <ul class=\"pkg-list artifact-list\" id=\"unix-run-list\">
    """
        for a in d.run_artifacts:
            yield """    <li class=\"artifact-row\">
      <div class=\"artifact-main\">
        <span class=\"artifact-open is-static\"><code>curl and run</code></span>
        <span class=\"muted artifact-meta\">"""
            yield str(a.path)
            yield """ · """
            yield str(a.size_str)
            yield """</span>
      </div>
      <pre class=\"ipxe-snippet\" tabindex=\"0\">curl -fsSL """
            yield str(d.cdn_base)
            yield """/artifacts/lead/"""
            yield str(a.path)
            yield """ -o metal-unix
chmod +x metal-unix
./metal-unix</pre>
    </li>
    """
        yield """  </ul>
</section>
"""
    if d.is_arch_seat and d.channel == "lead" and (d.has_elf or d.has_efi):
        yield """<section>
  <h2>Netboot (iPXE)</h2>
  <p class=\"muted\">
    Boot server holds NBP + <code>metal.ipxe</code> only; product images stay on this CDN (HTTPS).
    Inspect / download the images in <a href=\"#artifact-list\">Artifacts</a>.
  </p>
  <ul class=\"pkg-list artifact-list\" id=\"netboot-list\">
    <li class=\"artifact-row\">
      <div class=\"artifact-main\">
        <a class=\"artifact-open\" href=\""""
        yield str(d.cdn_base)
        yield """/static/netboot/undionly.kpxe\" download=\"undionly.kpxe\"><code>undionly.kpxe</code></a>
        <span class=\"muted artifact-meta\">BIOS · first-stage NBP (HTTPS-capable Metal build)</span>
      </div>
      <div class=\"artifact-actions\">
        <a class=\"icon-btn download-btn\" href=\""""
        yield str(d.cdn_base)
        yield """/static/netboot/undionly.kpxe\" download=\"undionly.kpxe\" title=\"Download undionly.kpxe\" aria-label=\"Download undionly.kpxe\">
          <svg viewBox=\"0 0 24 24\" width=\"18\" height=\"18\" aria-hidden=\"true\"><path fill=\"currentColor\" d=\"M12 3a1 1 0 0 1 1 1v9.59l3.3-3.3a1 1 0 1 1 1.4 1.42l-5 5a1 1 0 0 1-1.4 0l-5-5a1 1 0 1 1 1.4-1.42l3.3 3.3V4a1 1 0 0 1 1-1Zm-7 14a1 1 0 0 1 1 1v1h12v-1a1 1 0 1 1 2 0v2a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-2a1 1 0 0 1 1-1Z\"/></svg>
        </a>
      </div>
    </li>
    <li class=\"artifact-row\">
      <div class=\"artifact-main\">
        <a class=\"artifact-open\" href=\""""
        yield str(d.cdn_base)
        yield """/static/netboot/ipxe.efi\" download=\"ipxe.efi\"><code>ipxe.efi</code></a>
        <span class=\"muted artifact-meta\">UEFI · first-stage NBP (HTTPS-capable Metal build)</span>
      </div>
      <div class=\"artifact-actions\">
        <a class=\"icon-btn download-btn\" href=\""""
        yield str(d.cdn_base)
        yield """/static/netboot/ipxe.efi\" download=\"ipxe.efi\" title=\"Download ipxe.efi\" aria-label=\"Download ipxe.efi\">
          <svg viewBox=\"0 0 24 24\" width=\"18\" height=\"18\" aria-hidden=\"true\"><path fill=\"currentColor\" d=\"M12 3a1 1 0 0 1 1 1v9.59l3.3-3.3a1 1 0 1 1 1.4 1.42l-5 5a1 1 0 0 1-1.4 0l-5-5a1 1 0 1 1 1.4-1.42l3.3 3.3V4a1 1 0 0 1 1-1Zm-7 14a1 1 0 0 1 1 1v1h12v-1a1 1 0 1 1 2 0v2a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-2a1 1 0 0 1 1-1Z\"/></svg>
        </a>
      </div>
    </li>
    <li class=\"artifact-row\">
      <div class=\"artifact-main\">
        <a class=\"artifact-open\" href=\""""
        yield str(d.cdn_base)
        yield """/static/netboot/metal.ipxe\" download=\"metal.ipxe\"><code>metal.ipxe</code></a>
        <span class=\"muted artifact-meta\">iPXE script · chains CDN lead <code>arch.*.elf/efi</code></span>
      </div>
      <div class=\"artifact-actions\">
        <a class=\"icon-btn download-btn\" href=\""""
        yield str(d.cdn_base)
        yield """/static/netboot/metal.ipxe\" download=\"metal.ipxe\" title=\"Download metal.ipxe\" aria-label=\"Download metal.ipxe\">
          <svg viewBox=\"0 0 24 24\" width=\"18\" height=\"18\" aria-hidden=\"true\"><path fill=\"currentColor\" d=\"M12 3a1 1 0 0 1 1 1v9.59l3.3-3.3a1 1 0 1 1 1.4 1.42l-5 5a1 1 0 0 1-1.4 0l-5-5a1 1 0 1 1 1.4-1.42l3.3 3.3V4a1 1 0 0 1 1-1Zm-7 14a1 1 0 0 1 1 1v1h12v-1a1 1 0 1 1 2 0v2a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-2a1 1 0 0 1 1-1Z\"/></svg>
        </a>
      </div>
    </li>
    """
        for a in d.ipxe_artifacts:
            yield """    <li class=\"artifact-row\">
      <div class=\"artifact-main\">
        <span class=\"artifact-open is-static\"><code>"""
            if a.ends_efi:
                yield """UEFI · snippet"""
            else:
                yield """BIOS · snippet"""
            yield """</code></span>
        <span class=\"muted artifact-meta\">"""
            if a.ends_efi:
                yield """chain"""
            else:
                yield """kernel"""
            yield """ → copy into iPXE / metal.ipxe</span>
      </div>
      <pre class=\"ipxe-snippet\" tabindex=\"0\">#!ipxe
"""
            if a.ends_efi:
                yield """chain"""
            else:
                yield """kernel"""
            yield """ """
            yield str(d.cdn_base)
            yield """/artifacts/lead/"""
            yield str(a.path)
            yield """
boot</pre>
    </li>
    """
        yield """  </ul>
</section>
"""
    yield """<section>
  <h2>Artifacts</h2>
  <p class=\"muted\">
    """
    if d.is_arch_seat and d.name.endswith('.wasm'):
        yield """    Browser arch seat — <code>.mjs</code> / <code>.wasm</code> for the CDN shell <code>mp</code> pill. Click to inspect.
    """
    elif d.is_arch_seat:
        yield """    Freestanding arch seat images — click to inspect (sections / signature / hex). Download or use the Netboot rows above in iPXE.
    """
    else:
        yield """    Click a name to inspect pack guts. The commander navigates package · version · artifact · section · symbol with dual hex/asm/source views.
    """
    yield """  </p>
  <ul class=\"pkg-list artifact-list\" id=\"artifact-list\">
    """
    for a in d.entry.artifacts:
        yield """    <li class=\"artifact-row\"
        data-filename=\""""
        yield str(a.path)
        yield """\"
        data-package=\""""
        yield str(d.name)
        yield """\"
        data-channel=\""""
        yield str(d.channel)
        yield """\"
        """
        if d.channel != "lead":
            yield """data-version=\""""
            yield str(a.version_arg)
            yield """\""""
        yield """        data-inspect=\""""
        yield str(a.inspect_href)
        yield """\"
        data-files=\""""
        yield str(a.files_base)
        yield """\"
        data-files-raw=\""""
        yield str(a.files_raw)
        yield """\"
        data-sections-raw=\""""
        yield str(a.sections_raw)
        yield """\">
      <div class=\"artifact-main\">
        <button type=\"button\" class=\"artifact-open\" aria-expanded=\"false\">
          <code>"""
        yield str(a.path)
        yield """</code>
        </button>
        <span class=\"muted artifact-meta\">
          """
        if d.is_arch_seat and a.ends_efi_zlib:
            yield """UEFI twin · """
        elif d.is_arch_seat and a.ends_elf_zlib:
            yield """BIOS twin · """
        elif d.is_arch_seat and a.ends_efi:
            yield """UEFI · """
        elif d.is_arch_seat and a.ends_elf:
            yield """BIOS · """
        yield str(a.kind)
        yield """ · """
        yield str(a.encoding)
        yield """ · """
        yield str(a.size_str)
        yield """
        </span>
        <div class=\"artifact-actions\">
          <button type=\"button\" class=\"icon-btn inspect-open-btn\"
            data-filename=\""""
        yield str(a.path)
        yield """\"
            data-package=\""""
        yield str(d.name)
        yield """\"
            """
        if d.channel != "lead":
            yield """data-version=\""""
            yield str(a.version_arg)
            yield """\""""
        yield """            title=\"Inspect """
        yield str(a.path)
        yield """\"
            aria-label=\"Inspect """
        yield str(a.path)
        yield """\">
            <svg viewBox=\"0 0 24 24\" width=\"18\" height=\"18\" aria-hidden=\"true\">
              <path fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"
                d=\"M2.5 12s3.5-6.5 9.5-6.5S21.5 12 21.5 12s-3.5 6.5-9.5 6.5S2.5 12 2.5 12Z\"/>
              <circle cx=\"12\" cy=\"12\" r=\"3.25\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\"/>
            </svg>
          </button>
          <a class=\"icon-btn download-btn\" href=\""""
        yield str(a.dl_href)
        yield """\" download=\""""
        yield str(a.path)
        yield """\" title=\"Download """
        yield str(a.path)
        yield """\" aria-label=\"Download """
        yield str(a.path)
        yield """\">
            <svg viewBox=\"0 0 24 24\" width=\"18\" height=\"18\" aria-hidden=\"true\">
              <path fill=\"currentColor\" d=\"M12 3a1 1 0 0 1 1 1v9.59l3.3-3.3a1 1 0 1 1 1.4 1.42l-5 5a1 1 0 0 1-1.4 0l-5-5a1 1 0 1 1 1.4-1.42l3.3 3.3V4a1 1 0 0 1 1-1Zm-7 14a1 1 0 0 1 1 1v1h12v-1a1 1 0 1 1 2 0v2a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-2a1 1 0 0 1 1-1Z\"/>
            </svg>
          </a>
          """
        if d.show_try and a.is_wasm:
            yield """          <button type=\"button\" class=\"icon-btn try-btn\" data-mpy-try=\""""
            yield str(d.name)
            yield """\"
                  title=\"Try in µPy shell: import """
            yield str(d.name)
            yield """; exports("""
            yield str(d.name)
            yield """)\"
                  aria-label=\"Try """
            yield str(d.name)
            yield """ in MicroPython shell\">
            <svg viewBox=\"0 0 24 24\" width=\"18\" height=\"18\" aria-hidden=\"true\">
              <path fill=\"currentColor\" d=\"M8 5.14v14l11-7-11-7Z\"/>
            </svg>
          </button>
          """
        yield """        </div>
      </div>
      <div class=\"artifact-panel\" hidden></div>
    </li>
    """
    yield """  </ul>
</section>
"""
    if d.entry.contents:
        yield """<section>
  <h2>Package contents (index)</h2>
  <p class=\"muted\">
    """
        if d.entry.contents.name:
            yield """pack <code>"""
            yield str(d.entry.contents.name)
            yield """</code>"""
        yield """    """
        if d.entry.contents.pkg_version:
            yield """ · """
            yield str(d.entry.contents.pkg_version)
        yield """    · signed="""
        yield str(d.entry.contents.signed)
        yield """
    · pack="""
        yield str(d.entry.contents.has_pack)
        yield """
    · source="""
        yield str(d.entry.contents.has_source)
        yield """
  </p>
</section>
"""
    yield """
<dialog id=\"source-dialog\" class=\"source-dialog\">
  <form method=\"dialog\" class=\"source-dialog-head\">
    <strong id=\"source-dialog-title\">Source</strong>
    <div class=\"source-dialog-actions\">
      <a id=\"source-dialog-download\" class=\"icon-btn\" href=\"#\" download title=\"Download file\" aria-label=\"Download file\" hidden>
        <svg viewBox=\"0 0 24 24\" width=\"18\" height=\"18\" aria-hidden=\"true\">
          <path fill=\"currentColor\" d=\"M12 3a1 1 0 0 1 1 1v9.59l3.3-3.3a1 1 0 1 1 1.4 1.42l-5 5a1 1 0 0 1-1.4 0l-5-5a1 1 0 1 1 1.4-1.42l3.3 3.3V4a1 1 0 0 1 1-1Zm-7 14a1 1 0 0 1 1 1v1h12v-1a1 1 0 1 1 2 0v2a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-2a1 1 0 0 1 1-1Z\"/>
        </svg>
      </a>
      <button type=\"submit\" class=\"icon-btn\" value=\"close\" aria-label=\"Close\">✕</button>
    </div>
  </form>
  <div id=\"source-dialog-meta\" class=\"source-dialog-meta muted\" hidden></div>
  <pre id=\"source-dialog-body\" class=\"source-body\"></pre>
</dialog>

<script src=\""""
    yield str(d.vendor_0)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_1)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_2)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_3)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_4)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_5)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_6)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_7)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_8)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_9)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_10)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_11)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_12)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_13)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_14)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_15)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_16)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_17)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_18)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_19)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_20)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_21)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_22)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_23)
    yield """\"></script>
<script src=\""""
    yield str(d.vendor_24)
    yield """\"></script>
<script>
(() => """
    yield """{
  const list = document.getElementById(\"artifact-list\");
  if (!list) return;
  const dialog = document.getElementById(\"source-dialog\");
  const dialogTitle = document.getElementById(\"source-dialog-title\");
  const dialogBody = document.getElementById(\"source-dialog-body\");
  const dialogMeta = document.getElementById(\"source-dialog-meta\");
  const dialogDl = document.getElementById(\"source-dialog-download\");
  const HEX_PREVIEW = 65536;

  const DL_SVG = `<svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" aria-hidden=\"true\"><path fill=\"currentColor\" d=\"M12 3a1 1 0 0 1 1 1v9.59l3.3-3.3a1 1 0 1 1 1.4 1.42l-5 5a1 1 0 0 1-1.4 0l-5-5a1 1 0 1 1 1.4-1.42l3.3 3.3V4a1 1 0 0 1 1-1Zm-7 14a1 1 0 0 1 1 1v1h12v-1a1 1 0 1 1 2 0v2a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-2a1 1 0 0 1 1-1Z\"/></svg>`;
  /* Generic eye — Inspect opener (avoid star-in-circle branding lookalikes). */
  const INSP_SVG = `<svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" aria-hidden=\"true\"><path fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M2.5 12s3.5-6.5 9.5-6.5S21.5 12 21.5 12s-3.5 6.5-9.5 6.5S2.5 12 2.5 12Z\"/><circle cx=\"12\" cy=\"12\" r=\"3.25\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\"/></svg>`;

  function inspectBtnAttrs(ctx, extra) """
    yield """{
    const filename = (ctx && ctx.filename) || \"\";
    const pkg = (ctx && ctx.package) || \"\";
    const version = (ctx && ctx.version) || \"\";
    let attrs =
      ` data-filename=\"$"""
    yield """{esc(filename)}\" data-package=\"$"""
    yield """{esc(pkg)}\" data-version=\"$"""
    yield """{esc(version)}\"`;
    if (extra) attrs += \" \" + extra;
    return attrs;
  }
  function esc(s) """
    yield """{
    return String(s).replace(/[&<>\"']/g, (c) => ("""
    yield """{
      \"&\": \"&amp;\", \"<\": \"&lt;\", \">\": \"&gt;\", '\"': \"&quot;\", \"'\": \"&#39;\"
    })[c]);
  }

  function fmtSize(n) """
    yield """{
    const bytes = Number(n);
    if (!Number.isFinite(bytes) || bytes < 0) return \"?\";
    const exact = Math.trunc(bytes) + \" B\";
    if (bytes < 1024) return exact;
    const units = [\"KiB\", \"MiB\", \"GiB\", \"TiB\"];
    let value = bytes;
    let unit = units[0];
    for (let i = 0; i < units.length; i++) """
    yield """{
      value /= 1024;
      unit = units[i];
      if (value < 1024) break;
    }
    const pretty = value >= 100 ? value.toFixed(0)
      : value >= 10 ? value.toFixed(1)
      : value.toFixed(2);
    return pretty + \" \" + unit + \" (\" + exact + \")\";
  }

  function guessLang(path) """
    yield """{
    const lower = path.toLowerCase().replace(/\\\\/g, \"/\");
    const base = lower.split(\"/\").pop() || lower;
    if (base === \"makefile\" || base === \"gnumakefile\" || lower.endsWith(\".mk\")) return \"makefile\";
    if (base === \"cmakelists.txt\" || lower.endsWith(\".cmake\")) return \"cmake\";
    if (base === \"dockerfile\" || base.startsWith(\"dockerfile.\")) return \"dockerfile\";
    if (lower.endsWith(\".py\") || lower.endsWith(\".pyi\")) return \"python\";
    if (lower.endsWith(\".c\") || lower.endsWith(\".h\")) return \"c\";
    if (lower.endsWith(\".cc\") || lower.endsWith(\".cpp\") || lower.endsWith(\".cxx\")
        || lower.endsWith(\".hpp\") || lower.endsWith(\".hh\") || lower.endsWith(\".hxx\")
        || lower.endsWith(\".ipp\") || lower.endsWith(\".inl\")) return \"cpp\";
    if (lower.endsWith(\".rs\")) return \"rust\";
    if (lower.endsWith(\".ts\") || lower.endsWith(\".tsx\") || lower.endsWith(\".mts\") || lower.endsWith(\".cts\")) return \"typescript\";
    if (lower.endsWith(\".js\") || lower.endsWith(\".mjs\") || lower.endsWith(\".cjs\") || lower.endsWith(\".jsx\")) return \"javascript\";
    if (lower.endsWith(\".json\") || lower.endsWith(\".jsonc\") || lower.endsWith(\".json5\")) return \"json\";
    if (lower.endsWith(\".md\") || lower.endsWith(\".markdown\") || lower.endsWith(\".mdx\")) return \"markdown\";
    if (lower.endsWith(\".toml\") || lower.endsWith(\".ini\") || lower.endsWith(\".cfg\")
        || lower.endsWith(\".conf\") || base === \"pack.toml\") return \"ini\";
    if (lower.endsWith(\".yml\") || lower.endsWith(\".yaml\")) return \"yaml\";
    if (lower.endsWith(\".xml\") || lower.endsWith(\".html\") || lower.endsWith(\".htm\")
        || lower.endsWith(\".svg\") || lower.endsWith(\".xhtml\")) return \"xml\";
    if (lower.endsWith(\".sh\") || lower.endsWith(\".bash\") || lower.endsWith(\".zsh\")
        || lower.endsWith(\".ksh\") || base === \".bashrc\" || base === \".profile\") return \"bash\";
    if (lower.endsWith(\".diff\") || lower.endsWith(\".patch\")) return \"diff\";
    if (lower.endsWith(\".ll\")) return \"llvm\";
    if (lower.endsWith(\".go\")) return \"go\";
    if (lower.endsWith(\".java\")) return \"java\";
    if (lower.endsWith(\".sql\")) return \"sql\";
    if (lower.endsWith(\".rb\") || lower.endsWith(\".rake\")) return \"ruby\";
    if (lower.endsWith(\".pl\") || lower.endsWith(\".pm\")) return \"perl\";
    if (lower.endsWith(\".wat\") || lower.endsWith(\".wast\")) return \"lisp\";
    if (lower.endsWith(\".s\") || lower.endsWith(\".asm\")) return \"x86asm\";
    return \"\";
  }

  function fileRow(path, filesBase, filesRaw, metaHtml, ctx) """
    yield """{
    const rawUrl = filesRaw + \"?path=\" + encodeURIComponent(path);
    const base = path.split(\"/\").pop() || path;
    const isMpy = /\\.mpy$/i.test(path);
    let inspBtn = \"\";
    if (ctx) """
    yield """{
      const common =
        ` data-filename=\"$"""
    yield """{esc(ctx.filename || \"\")}\" data-package=\"$"""
    yield """{esc(ctx.package || \"\")}\" data-version=\"$"""
    yield """{esc(ctx.version || \"\")}\"`;
      if (isMpy) """
    yield """{
        inspBtn =
          `<button type=\"button\" class=\"icon-btn mpy-inspect-btn\"$"""
    yield """{common} data-mpy-path=\"$"""
    yield """{esc(path)}\" title=\"mpy-dis in Inspect\" aria-label=\"Inspect $"""
    yield """{esc(path)}\">$"""
    yield """{INSP_SVG}</button>`;
      } else """
    yield """{
        inspBtn =
          `<button type=\"button\" class=\"icon-btn inspect-open-btn\"$"""
    yield """{common} data-source-path=\"$"""
    yield """{esc(path)}\" title=\"Inspect $"""
    yield """{esc(path)}\" aria-label=\"Inspect $"""
    yield """{esc(path)}\">$"""
    yield """{INSP_SVG}</button>`;
      }
    }
    return `<li>
      <button type=\"button\" class=\"file-link\" data-path=\"$"""
    yield """{esc(path)}\" data-files=\"$"""
    yield """{esc(filesBase)}\" data-files-raw=\"$"""
    yield """{esc(filesRaw)}\" title=\"Open $"""
    yield """{esc(path)}\">$"""
    yield """{esc(path)}</button>
      <span class=\"muted\">$"""
    yield """{metaHtml}</span>
      $"""
    yield """{inspBtn}
      <a class=\"icon-btn file-download\" href=\"$"""
    yield """{esc(rawUrl)}\" download=\"$"""
    yield """{esc(base)}\" title=\"Download $"""
    yield """{esc(path)}\" aria-label=\"Download $"""
    yield """{esc(path)}\">$"""
    yield """{DL_SVG}</a>
    </li>`;
  }

  function sectionRow(sec, sectionsRaw, ctx) """
    yield """{
    const rawUrl = sectionsRaw + \"?index=\" + encodeURIComponent(String(sec.index));
    const role = sec.role || \"other\";
    const roleCls = role === \"code\" ? \" sec-code\" : (role === \"meta\" ? \" sec-meta\" : \"\");
    const dlName = (sec.name || (\"section_\" + sec.index)).replace(/\\//g, \"_\");
    const insp = ctx
      ? `<button type=\"button\" class=\"icon-btn inspect-open-btn\"$"""
    yield """{inspectBtnAttrs(ctx, `data-section-index=\"$"""
    yield """{esc(sec.index)}\"`)} title=\"Inspect section $"""
    yield """{esc(sec.name)}\" aria-label=\"Inspect section $"""
    yield """{esc(sec.name)}\">$"""
    yield """{INSP_SVG}</button>`
      : \"\";
    return `<li class=\"section-row$"""
    yield """{roleCls}\">
      <button type=\"button\" class=\"section-link\" data-index=\"$"""
    yield """{esc(sec.index)}\" data-name=\"$"""
    yield """{esc(sec.name)}\" data-sections-raw=\"$"""
    yield """{esc(sectionsRaw)}\" data-size=\"$"""
    yield """{esc(sec.size)}\" data-role=\"$"""
    yield """{esc(role)}\" title=\"Inspect section: $"""
    yield """{esc(sec.name)}\">$"""
    yield """{esc(sec.name)}</button>
      <span class=\"muted\">$"""
    yield """{esc(role)} · type=$"""
    yield """{esc(sec.type_id)} · $"""
    yield """{esc(fmtSize(sec.size))}</span>
      $"""
    yield """{insp}
      <a class=\"icon-btn file-download\" href=\"$"""
    yield """{esc(rawUrl)}\" download=\"$"""
    yield """{esc(dlName)}\" title=\"Download section $"""
    yield """{esc(sec.name)}\" aria-label=\"Download section $"""
    yield """{esc(sec.name)}\">$"""
    yield """{DL_SVG}</a>
    </li>`;
  }

  function renderInspect(data, filesBase, filesRaw, sectionsRaw, ctx) """
    yield """{
    const packFiles = (data.pack && data.pack.files) || [];
    const sourceFiles = (data.source && data.source.files) || [];
    const exports = (data.pack && data.pack.exports) || [];
    const imports = data.imports || [];
    const sections = data.sections || [];
    const symbols = data.symbols || [];
    const filename = (ctx && ctx.filename) || \"\";
    const version = (ctx && ctx.version) || \"\";
    const pkg = (ctx && ctx.package) || \"\";
    let html = `<div class=\"guts\">
      <p class=\"muted\">
        kind=<code>$"""
    yield """{esc(data.kind)}</code>
        · encoding=<code>$"""
    yield """{esc(data.encoding)}</code>
        · signed=<code>$"""
    yield """{esc(data.signed)}</code>
        · naked=$"""
    yield """{esc(fmtSize(data.naked_size))}
        $"""
    yield """{data.aot_version != null ? \" · aot=\" + esc(data.aot_version) : \"\"}
        $"""
    yield """{data.has_dwarf ? \" · dwarf\" : \"\"}
      </p>`;
    if (data.error) html += `<p class=\"muted\">error: $"""
    yield """{esc(data.error)}</p>`;
    if (symbols.length || sections.length) """
    yield """{
      html += `<p class=\"inspect-toolbar\"><button type=\"button\" class=\"icon-btn inspect-open-btn\"
        data-filename=\"$"""
    yield """{esc(filename)}\"
        data-package=\"$"""
    yield """{esc(pkg)}\"
        data-version=\"$"""
    yield """{esc(version)}\"
        title=\"Open Inspect commander\"
        aria-label=\"Open Inspect commander\">$"""
    yield """{INSP_SVG}</button>
        <span class=\"muted\">Open Inspect…</span></p>`;
    }
    if (symbols.length) """
    yield """{
      html += `<h3>Symbols <span class=\"muted\">($"""
    yield """{symbols.length})</span></h3>
        <ul class=\"file-tree\">`;
      for (const sym of symbols) """
    yield """{
        const meta = [sym.kind, sym.binding, fmtSize(sym.size || 0)].filter(Boolean).join(\" · \");
        html += `<li>
          <button type=\"button\" class=\"symbol-link\"
            data-filename=\"$"""
    yield """{esc(filename)}\"
            data-package=\"$"""
    yield """{esc(pkg)}\"
            data-version=\"$"""
    yield """{esc(version)}\"
            data-symbol=\"$"""
    yield """{esc(sym.name)}\"
            data-section-index=\"$"""
    yield """{esc(sym.section_index == null ? \"\" : sym.section_index)}\"
            data-offset=\"$"""
    yield """{esc(sym.offset == null ? 0 : sym.offset)}\"
            title=\"Inspect $"""
    yield """{esc(sym.name)}\"><code>$"""
    yield """{esc(sym.name)}</code></button>
          <span class=\"muted\">$"""
    yield """{esc(meta)}</span>
          <button type=\"button\" class=\"icon-btn inspect-open-btn\"
            data-filename=\"$"""
    yield """{esc(filename)}\"
            data-package=\"$"""
    yield """{esc(pkg)}\"
            data-version=\"$"""
    yield """{esc(version)}\"
            data-symbol=\"$"""
    yield """{esc(sym.name)}\"
            data-section-index=\"$"""
    yield """{esc(sym.section_index == null ? \"\" : sym.section_index)}\"
            data-offset=\"$"""
    yield """{esc(sym.offset == null ? 0 : sym.offset)}\"
            title=\"Inspect $"""
    yield """{esc(sym.name)}\"
            aria-label=\"Inspect $"""
    yield """{esc(sym.name)}\">$"""
    yield """{INSP_SVG}</button>
        </li>`;
      }
      html += `</ul>`;
    }
    if (sections.length) """
    yield """{
      html += `<h3>Sections <span class=\"muted\">($"""
    yield """{sections.length})</span></h3>
        <ul class=\"file-tree\">`;
      for (const sec of sections) """
    yield """{
        html += sectionRow(sec, sectionsRaw, ctx);
      }
      html += `</ul>`;
    }
    if (data.pack) """
    yield """{
      html += `<h3>Pack <code>$"""
    yield """{esc(data.pack.name)}</code> (v$"""
    yield """{esc(data.pack.version)})</h3>
        <ul class=\"file-tree\">`;
      for (const f of packFiles) """
    yield """{
        html += fileRow(
          f.path, filesBase, filesRaw,
          `$"""
    yield """{esc(f.kind)} · $"""
    yield """{esc(fmtSize(f.raw_len))}`,
          ctx
        );
      }
      html += `</ul>`;
      if (exports.length) """
    yield """{
        html += `<h4>Exports</h4><ul class=\"file-tree\">`;
        for (const ex of exports) """
    yield """{
          const name = ex.export || ex.func;
          const typeLabel = ex.typesig || (ex.sig === 255 ? \"auto\" : (\"tag:\" + ex.sig));
          html += `<li>
            <button type=\"button\" class=\"symbol-link\"
              data-filename=\"$"""
    yield """{esc(filename)}\"
              data-package=\"$"""
    yield """{esc(pkg)}\"
              data-version=\"$"""
    yield """{esc(version)}\"
              data-symbol=\"$"""
    yield """{esc(name)}\"
              title=\"Inspect export $"""
    yield """{esc(name)}\"><code>$"""
    yield """{esc(name)}</code></button>
            <span class=\"muted\">$"""
    yield """{esc(typeLabel)}</span>
            <button type=\"button\" class=\"icon-btn inspect-open-btn\"
              data-filename=\"$"""
    yield """{esc(filename)}\"
              data-package=\"$"""
    yield """{esc(pkg)}\"
              data-version=\"$"""
    yield """{esc(version)}\"
              data-symbol=\"$"""
    yield """{esc(name)}\"
              title=\"Inspect export $"""
    yield """{esc(name)}\"
              aria-label=\"Inspect export $"""
    yield """{esc(name)}\">$"""
    yield """{INSP_SVG}</button>
          </li>`;
        }
        html += `</ul>`;
      }
    }
    if (data.source) """
    yield """{
      const tags = data.source.tags || """
    yield """{};
      const tagBits = Object.keys(tags).map((k) => `$"""
    yield """{esc(k)}=$"""
    yield """{esc(tags[k])}`).join(\" · \");
      html += `<h3>Source tree <code>$"""
    yield """{esc(data.source.name)}</code> $"""
    yield """{esc(data.source.pkg_version || \"\")}$"""
    yield """{
        tagBits ? ` <span class=\"muted\">$"""
    yield """{tagBits}</span>` : \"\"
      }</h3>
        <ul class=\"file-tree\">`;
      for (const f of sourceFiles) """
    yield """{
        html += fileRow(f.path, filesBase, filesRaw, esc(fmtSize(f.raw_len)), ctx);
      }
      html += `</ul>`;
    }
    if (imports.length) """
    yield """{
      html += `<h4>Imports <span class=\"muted\">(guest→guest call graph)</span></h4><ul class=\"file-tree\">`;
      for (const im of imports) """
    yield """{
        html += `<li><code>$"""
    yield """{esc(im.module)}.$"""
    yield """{esc(im.func)}</code></li>`;
      }
      html += `</ul>`;
    }
    const deps = data.deps || [];
    if (deps.length) """
    yield """{
      html += `<h4>Dependencies <span class=\"muted\">(wasmmod.deps)</span></h4><ul class=\"file-tree\">`;
      for (const d of deps) """
    yield """{
        html += `<li><code>$"""
    yield """{esc(d.name)}</code> <span class=\"muted\">== $"""
    yield """{esc(d.version)}</span></li>`;
      }
      html += `</ul>`;
    }
    if (data.sig) """
    yield """{
      const s = data.sig;
      const fmt = s.format === \"mpws\"
        ? `MPWS v$"""
    yield """{esc(s.version ?? \"?\")}`
        : \"raw ECDSA\";
      html += `<h3>Signature <code>wasmmod.sig</code></h3>
        <p class=\"muted\">
          format=<code>$"""
    yield """{fmt}</code>
          · flags=<code>$"""
    yield """{esc(s.flags)}</code>
          · payload=$"""
    yield """{esc(fmtSize(s.payload_len))}
        </p>
        <ul class=\"file-tree\">
          <li>digest covers <span class=\"muted\">$"""
    yield """{esc(fmtSize(s.signed_len))}</span>
            <span class=\"muted\">(module bytes with embedded wasmmod.sig section stripped)</span></li>
          <li>ECDSA sig <span class=\"muted\">$"""
    yield """{esc(fmtSize(s.sig_len))} · sha256=$"""
    yield """{esc(s.sig_sha256)}</span></li>
          <li>chain <span class=\"muted\">$"""
    yield """{esc(fmtSize(s.chain_len))} · $"""
    yield """{(s.certs || []).length} cert(s)</span></li>
        </ul>`;
      if ((s.certs || []).length) """
    yield """{
        html += `<h4>Certificate chain</h4><ul class=\"file-tree\">`;
        for (const c of s.certs) """
    yield """{
          const role = c.role === \"leaf\" ? \"leaf\" : `intermediate[$"""
    yield """{c.index}]`;
          html += `<li><code>[$"""
    yield """{esc(c.index)} $"""
    yield """{role}]</code>
            <span class=\"muted\">$"""
    yield """{esc(fmtSize(c.der_len))} · sha256=$"""
    yield """{esc(c.sha256)}</span></li>`;
        }
        html += `</ul>`;
      }
    } else if (data.sig_error) """
    yield """{
      html += `<h3>Signature <code>wasmmod.sig</code></h3>
        <p class=\"muted\">error: $"""
    yield """{esc(data.sig_error)}</p>`;
    }
    if (!data.pack && !data.source && !data.sig && !data.error && !data.sig_error && !sections.length) """
    yield """{
      html += `<p class=\"muted\">No wasmmod.pack / wasmmod.source / wasmmod.sig sections in this artifact.</p>`;
    }
    html += `</div>`;
    return html;
  }

  function hexdumpHtml(buf, limit) """
    yield """{
    if (window.MetalInspect && window.MetalInspect.hexdumpHtml) """
    yield """{
      return window.MetalInspect.hexdumpHtml(buf, limit);
    }
    const view = buf.byteLength > limit ? buf.slice(0, limit) : buf;
    const u8 = new Uint8Array(view);
    const width = 16;
    const lines = [];
    for (let i = 0; i < u8.length; i += width) """
    yield """{
      const chunk = u8.subarray(i, i + width);
      const hex = Array.from(chunk, (b) => """
    yield """{
        const hx = b.toString(16).padStart(2, \"0\");
        if (b === 0) return `<span class=\"hx-null\">$"""
    yield """{hx}</span>`;
        if (b >= 32 && b < 127) return `<span class=\"hx-print\">$"""
    yield """{hx}</span>`;
        return `<span class=\"hx-hi\">$"""
    yield """{hx}</span>`;
      }).join(\" \");
      const pad = \"   \".repeat(width - chunk.length);
      let ascii = \"\";
      for (const b of chunk) ascii += (b >= 32 && b < 127) ? String.fromCharCode(b) : \".\";
      lines.push(
        `<span class=\"hx-off\">$"""
    yield """{i.toString(16).padStart(8, \"0\")}</span>  $"""
    yield """{hex}$"""
    yield """{pad}  |$"""
    yield """{esc(ascii)}|`
      );
    }
    let html = lines.join(\"\\n\");
    if (buf.byteLength > limit) """
    yield """{
      html += `\\n… showing $"""
    yield """{limit} of $"""
    yield """{buf.byteLength} bytes`;
    }
    return html;
  }

  function openInspectFromBtn(btn) """
    yield """{
    if (!window.openInspect) return;
    const version = btn.dataset.version || undefined;
    const sectionRaw = btn.dataset.sectionIndex;
    const sourcePath = btn.dataset.sourcePath || undefined;
    const mpyPath = btn.dataset.mpyPath || undefined;
    window.openInspect("""
    yield """{
      package: btn.dataset.package || undefined,
      filename: btn.dataset.filename,
      version: version || undefined,
      symbol: btn.dataset.symbol || undefined,
      mpyPath,
      sourcePath,
      addr: btn.dataset.offset != null && btn.dataset.offset !== \"\"
        ? Number(btn.dataset.offset) : undefined,
      sectionIndex: sectionRaw !== \"\" && sectionRaw != null ? Number(sectionRaw) : undefined,
      tab: mpyPath ? \"asm\" : (sourcePath ? \"source\" : undefined),
    });
  }

  function setDownload(rawUrl, filename) """
    yield """{
    dialogDl.hidden = false;
    dialogDl.href = rawUrl;
    dialogDl.setAttribute(\"download\", filename);
  }

  function resetSourceBody(className, text) """
    yield """{
    // hljs 11 refuses to re-highlight if dataset.highlighted is still set.
    delete dialogBody.dataset.highlighted;
    dialogBody.className = className || \"source-body\";
    dialogBody.textContent = text == null ? \"\" : text;
  }

  function paintSource(text, lang) """
    yield """{
    delete dialogBody.dataset.highlighted;
    if (window.hljs && lang && window.hljs.getLanguage(lang)) """
    yield """{
      try """
    yield """{
        const out = window.hljs.highlight(text, """
    yield """{ language: lang, ignoreIllegals: true });
        dialogBody.className = \"source-body hljs language-\" + lang;
        dialogBody.innerHTML = out.value;
        dialogBody.dataset.highlighted = \"yes\";
        return;
      } catch (err) """
    yield """{
        console.warn(\"hljs highlight failed\", lang, err);
      }
    }
    dialogBody.className = \"source-body\" + (lang ? (\" language-\" + lang) : \"\");
    dialogBody.textContent = text;
  }

  async function openSource(filesBase, filesRaw, path) """
    yield """{
    dialogTitle.textContent = path;
    resetSourceBody(\"source-body\", \"Loading…\");
    dialogMeta.hidden = true;
    dialogMeta.textContent = \"\";
    setDownload(filesRaw + \"?path=\" + encodeURIComponent(path), path.split(\"/\").pop() || path);
    dialog.showModal();

    const metaUrl = filesBase + \"?path=\" + encodeURIComponent(path);
    const res = await fetch(metaUrl, """
    yield """{ headers: """
    yield """{ Accept: \"application/json\" } });
    const data = await res.json().catch(() => ("""
    yield """{}));
    if (!res.ok) """
    yield """{
      resetSourceBody(\"source-body\", data.detail || (\"failed (\" + res.status + \")\"));
      return;
    }

    const isBinary = !!(data.binary || data.text == null);
    dialogMeta.hidden = false;
    dialogMeta.textContent =
      (isBinary ? \"binary\" : \"text\") +
      \" · \" + fmtSize(data.size || 0) +
      \" · section \" + (data.section || \"?\") +
      (data.kind ? (\" · kind \" + data.kind) : \"\");

    if (!isBinary) """
    yield """{
      paintSource(data.text, guessLang(path));
      return;
    }

    const rawUrl = filesRaw + \"?path=\" + encodeURIComponent(path);
    const rawRes = await fetch(rawUrl, """
    yield """{ headers: """
    yield """{ Accept: \"application/octet-stream\" } });
    if (!rawRes.ok) """
    yield """{
      resetSourceBody(
        \"source-body\",
        `(binary $"""
    yield """{fmtSize(data.size || 0)} — download failed $"""
    yield """{rawRes.status})`
      );
      return;
    }
    const buf = await rawRes.arrayBuffer();
    delete dialogBody.dataset.highlighted;
    dialogBody.className = \"source-body hex-body\";
    dialogBody.innerHTML = hexdumpHtml(buf, HEX_PREVIEW);
  }

  async function openSection(sectionsRaw, index, name, size, role) """
    yield """{
    const title = name || (\"section_\" + index);
    dialogTitle.textContent = title;
    resetSourceBody(\"source-body\", \"Loading…\");
    dialogMeta.hidden = false;
    dialogMeta.textContent =
      \"container section · \" + (role || \"other\") +
      \" · index \" + index +
      \" · \" + fmtSize(size || 0);
    const rawUrl = sectionsRaw + \"?index=\" + encodeURIComponent(String(index));
    setDownload(rawUrl, title.replace(/\\//g, \"_\"));
    dialog.showModal();

    const rawRes = await fetch(rawUrl, """
    yield """{ headers: """
    yield """{ Accept: \"application/octet-stream\" } });
    if (!rawRes.ok) """
    yield """{
      const err = await rawRes.json().catch(() => ("""
    yield """{}));
      resetSourceBody(
        \"source-body\",
        err.detail || (\"failed to load section (\" + rawRes.status + \")\")
      );
      return;
    }
    const buf = await rawRes.arrayBuffer();
    delete dialogBody.dataset.highlighted;
    dialogBody.className = \"source-body hex-body\";
    dialogBody.innerHTML = hexdumpHtml(buf, HEX_PREVIEW);
  }

  list.addEventListener(\"click\", async (ev) => """
    yield """{
    if (ev.target.closest(\".file-download\") || ev.target.closest(\".download-btn\") || ev.target.closest(\".try-btn\")) return;
    const inspBtn = ev.target.closest(\".symbol-link, .inspect-open-btn, .mpy-inspect-btn\");
    if (inspBtn) """
    yield """{
      ev.preventDefault();
      openInspectFromBtn(inspBtn);
      return;
    }
    const secBtn = ev.target.closest(\".section-link\");
    if (secBtn) """
    yield """{
      ev.preventDefault();
      const row = secBtn.closest(\".artifact-row\");
      if (window.openInspect && row) """
    yield """{
        window.openInspect("""
    yield """{
          package: row.dataset.package,
          filename: row.dataset.filename,
          version: row.dataset.version || undefined,
          sectionIndex: Number(secBtn.dataset.index),
          tab: \"hex\",
        });
        return;
      }
      openSection(
        secBtn.dataset.sectionsRaw,
        Number(secBtn.dataset.index),
        secBtn.dataset.name,
        Number(secBtn.dataset.size),
        secBtn.dataset.role
      );
      return;
    }
    const fileBtn = ev.target.closest(\".file-link\");
    if (fileBtn) """
    yield """{
      ev.preventDefault();
      openSource(fileBtn.dataset.files, fileBtn.dataset.filesRaw, fileBtn.dataset.path);
      return;
    }
    const openBtn = ev.target.closest(\".artifact-open\");
    if (!openBtn) return;
    const row = openBtn.closest(\".artifact-row\");
    const panel = row.querySelector(\".artifact-panel\");
    const expanded = openBtn.getAttribute(\"aria-expanded\") === \"true\";
    if (expanded) """
    yield """{
      openBtn.setAttribute(\"aria-expanded\", \"false\");
      panel.hidden = true;
      return;
    }
    openBtn.setAttribute(\"aria-expanded\", \"true\");
    panel.hidden = false;
    if (!panel.dataset.loaded) """
    yield """{
      panel.innerHTML = `<p class=\"muted\">Inspecting…</p>`;
      try """
    yield """{
        const res = await fetch(row.dataset.inspect, """
    yield """{ headers: """
    yield """{ Accept: \"application/json\" } });
        const data = await res.json();
        if (!res.ok) throw new Error(data.detail || res.status);
        panel.innerHTML = renderInspect(
          data, row.dataset.files, row.dataset.filesRaw, row.dataset.sectionsRaw,
          """
    yield """{
            filename: row.dataset.filename,
            package: row.dataset.package,
            version: row.dataset.version || \"\",
          }
        );
        panel.dataset.loaded = \"1\";
      } catch (err) """
    yield """{
        panel.innerHTML = `<p class=\"muted\">Inspect failed: $"""
    yield """{esc(err.message || err)}</p>`;
      }
    }
  });
})();
</script>
"""
