# Autogenerated file
def render(d):
    yield """<section class=\"hero\">
  <p class=\"eyebrow\">shell</p>
  <h1>Sessions</h1>
  <p class=\"lede\">
    Browser REPL / CDN loader sessions for
    <strong>"""
    yield str(d.principal_label)
    yield """</strong>"""
    if d.principal_web_id:
        yield """    <code class=\"muted\" title=\"web session principal id\">["""
        yield str(d.principal_web_id)
        yield """]</code>"""
    yield """.
    Hits in the last 30 minutes (pack loads, index fetches, Try / autoexec).
  </p>
</section>

"""
    if not d.shell_sessions:
        yield """<p class=\"muted\">No shell sessions yet — open the µPy panel to bind a CDN loader.</p>
"""
    else:
        yield """<ul class=\"session-list\">
  """
        for s in d.shell_sessions:
            yield """  <li class=\"session-card\">
    <header class=\"session-card-head\">
      <code class=\"session-id\" title=\""""
            yield str(s.full_id)
            yield """\">"""
            yield str(s.id_short)
            yield """</code>
      <span class=\"muted\">"""
            yield str(s.principal_label)
            yield """</span>
      <span class=\"muted session-time\">last """
            yield str(s.last_activity_at)
            yield """</span>
    </header>
    <div class=\"session-loader\">
      <p class=\"session-loader-label\">loader entered</p>
      <ul class=\"session-tree\">
        <li><span class=\"k\">base</span> <code>"""
            yield str(s.base_disp)
            yield """</code></li>
        <li><span class=\"k\">channel</span> <code>"""
            yield str(s.channel)
            yield """</code></li>
        <li><span class=\"k\">driver</span> <code>"""
            yield str(s.driver_disp)
            yield """</code></li>
      </ul>
    </div>
    """
            if s.spark:
                yield """    <div class=\"session-spark\" role=\"img\" aria-label=\"Hits over last """
                yield str(s.window_minutes)
                yield """ minutes\">
      """
                for b in s.spark:
                    yield """      <span
        class=\"session-spark-bar"""
                    if b.count:
                        yield """ is-hot"""
                    yield """\"
        style=\"--h: """
                    yield str(b.height)
                    yield """%\"
        title=\""""
                    yield str(b.minute)
                    yield """ · """
                    yield str(b.count)
                    yield """\"
      ></span>
      """
                yield """    </div>
    <p class=\"muted session-spark-caption\">
      """
                yield str(s.recent_len)
                yield """ event(s) in window
      """
                if s.last_kind:
                    yield """      · last
      <code>"""
                    yield str(s.last_kind)
                    if s.last_package:
                        yield """ """
                        yield str(s.last_package)
                    yield """</code>
      """
                yield """    </p>
    """
                if s.recent:
                    yield """    <ul class=\"session-events\">
      """
                    for ev in s.recent:
                        yield """      <li>
        <span class=\"session-ev-kind\">"""
                        yield str(ev.kind)
                        yield """</span>
        """
                        if ev.package:
                            yield """<code>"""
                            yield str(ev.package)
                            yield """</code>"""
                        elif ev.path:
                            yield """<code class=\"muted\">"""
                            yield str(ev.path)
                            yield """</code>"""
                        yield """      </li>
      """
                    yield """    </ul>
    """
                yield """    """
            yield """  </li>
  """
        yield """</ul>
"""
