# Autogenerated file
def render(d):
    yield """<!DOCTYPE html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
  <title>"""
    yield str(d.title)
    yield """</title>
  <link rel=\"stylesheet\" href=\""""
    yield str(d.site_css)
    yield """\" />
  """
    yield str(d.page_head)
    yield """
</head>
<body class=\""""
    yield str(d.body_class)
    yield """\" data-base-path=\""""
    yield str(d.base_path)
    yield """\">
  <div class=\"site-top\">
    """
    if d.experimental:
        yield """    <div class=\"exp-banner\" role=\"status\">
      <strong>Experimental</strong>
      <span>"""
        yield str(d.experimental_message)
        yield """</span>
    </div>
    """
    yield """    <header class=\"banner\">
      <a class=\"brand\" href=\""""
    yield str(d.home_href)
    yield """\">
        <img class=\"brand-mark\" src=\""""
    yield str(d.brand_logo)
    yield """\" width=\"22\" height=\"22\" alt=\"\" decoding=\"async\" referrerpolicy=\"no-referrer\" crossorigin=\"anonymous\" />
        """
    yield str(d.brand_name)
    yield """
      </a>
      <nav class=\"top-nav\">
        <a href=\""""
    yield str(d.nav_browse)
    yield """\" class=\""""
    yield str(d.nav_browse_cls)
    yield """\">Browse</a>
        """
    if d.nav_users:
        yield """<a href=\""""
        yield str(d.nav_users)
        yield """\" class=\""""
        yield str(d.nav_users_cls)
        yield """\">Users</a>"""
    yield """        """
    if d.nav_publish:
        yield """<a href=\""""
        yield str(d.nav_publish)
        yield """\" class=\""""
        yield str(d.nav_publish_cls)
        yield """\">Publish</a>"""
    yield """        """
    if d.nav_federation:
        yield """        <a href=\""""
        yield str(d.nav_federation)
        yield """\" class=\""""
        yield str(d.nav_federation_cls)
        yield """\">Federation</a>
        """
    yield """        """
    if d.nav_sessions:
        yield """<a href=\""""
        yield str(d.nav_sessions)
        yield """\" class=\""""
        yield str(d.nav_sessions_cls)
        yield """\">Sessions</a>"""
    yield """        <a href=\""""
    yield str(d.nav_docs)
    yield """\" class=\""""
    yield str(d.nav_docs_cls)
    yield """\">API</a>
        """
    if d.current_user:
        yield """        <span class=\"nav-user\" title=\""""
        yield str(d.user_email)
        yield """\">"""
        yield str(d.user_email)
        yield """</span>
        <button type=\"button\" class=\"nav-logout\" id=\"nav-logout\">Logout</button>
        """
    elif d.nav_login:
        yield """        <a href=\""""
        yield str(d.nav_login)
        yield """\" class=\""""
        yield str(d.nav_login_cls)
        yield """\">Login</a>
        """
    yield """      </nav>
    </header>
  </div>

  <div class=\"shell\">
    <aside
      class=\"sidebar\"
      aria-label=\"Package tree\"
      id=\"pkg-nav\"
      data-active=\""""
    yield str(d.active_package)
    yield """\"
    >
      <p class=\"sidebar-label\">Packages</p>
      <label class=\"tree-filter\">
        <span class=\"visually-hidden\">Filter packages</span>
        <input
          type=\"search\"
          id=\"pkg-nav-filter\"
          placeholder=\"Filter packages…\"
          autocomplete=\"off\"
          spellcheck=\"false\"
        />
      </label>
      <p class=\"tree-filter-empty\" id=\"pkg-nav-filter-empty\" hidden>No matches</p>
      """
    if d.content_nav:
        yield """      """
        yield str(d.content_nav)
        yield """
      """
    else:
        yield """      <p class=\"tree-empty\">No packages yet</p>
      """
    yield """    </aside>

    <main class=\""""
    yield str(d.main_class)
    yield """\">
      """
    yield str(d.content)
    yield """
    </main>
  </div>

  <footer>
    <div class=\"footer-product\">
      <span class=\"product\">"""
    yield str(d.brand_name)
    yield """</span>
      <span class=\"footer-ver\" title=\"package version\">"""
    yield str(d.app_version)
    yield """</span>
    </div>
    <nav class=\"footer-links\" aria-label=\"Project links\">
      <a href=\"https://github.com/pymergetic-wasmmod/wasmmod-cdn\" rel=\"noopener\" target=\"_blank\">GitHub</a>
      <a href=\"https://pypi.org/project/pymergetic-wasmmod-cdn/\" rel=\"noopener\" target=\"_blank\">PyPI</a>
      <a href=\"https://github.com/pymergetic-wasmmod/wasmmod\" rel=\"noopener\" target=\"_blank\">wasmmod</a>
    </nav>
    <a class=\"footer-health\" href=\""""
    yield str(d.health_href)
    yield """\" title=\"service health\">
      <span class=\"health-dot\" aria-hidden=\"true\"></span>
      <span>ok</span>
    </a>
  </footer>

  """
    if d.experimental_repl:
        yield """  <div
    id=\"mpy-repl\"
    class=\"mpy-repl is-mini\"
    aria-expanded=\"false\"
    data-base-path=\""""
        yield str(d.base_path)
        yield """\"
    data-cdn-base=\""""
        yield str(d.cdn_base)
        yield """\"
    data-mjs-url=\""""
        yield str(d.repl_mjs_url)
        yield """\"
    data-repl-asset-v=\""""
        yield str(d.repl_asset_v)
        yield """\"
    data-repl-engine=\""""
        yield str(d.repl_default_engine)
        yield """\"
    data-autoexec-url=\""""
        yield str(d.repl_autoexec)
        yield """\"
  >
    <div class=\"mpy-repl-bar\">
      <div class=\"mpy-repl-engines\" role=\"group\" aria-label=\"µPy engine\">
        """
        for e in d.repl_engines:
            yield """        <button
          type=\"button\"
          class=\"mpy-repl-engine"""
            if e.id == d.repl_default_engine:
                yield """ is-active"""
            yield """\"
          data-mpy-engine=\""""
            yield str(e.id)
            yield """\"
          data-mjs-href=\""""
            yield str(e.mjs_href)
            yield """\"
          title=\""""
            yield str(e.title)
            yield """\"
          """
            if not e.ready:
                yield """disabled"""
            yield """        >"""
            yield str(e.label)
            yield """</button>
        """
        yield """      </div>
      <label class=\"mpy-repl-heap\" title=\"GC heap for the focused engine (restarts that engine)\">
        <span class=\"visually-hidden\">Heap size</span>
        <select id=\"mpy-repl-heap\" aria-label=\"GC heap size for focused engine\">
          <option value=\"4194304\">4M</option>
          <option value=\"8388608\">8M</option>
          <option value=\"16777216\">16M</option>
          <option value=\"33554432\">32M</option>
          <option value=\"67108864\">64M</option>
          <option value=\"134217728\">128M</option>
        </select>
      </label>
      <button type=\"button\" id=\"mpy-repl-reset\" class=\"mpy-repl-reset\" title=\"Reset seat after shutdown (reboot / boot again)\" hidden>Reset</button>
      <button type=\"button\" id=\"mpy-repl-toggle\" class=\"mpy-repl-toggle\" title=\"Toggle MicroPython shell size\">
        <span class=\"mpy-repl-title\">µPy</span>
        <span id=\"mpy-repl-status\" class=\"mpy-repl-status muted\">"""
        if d.repl_ready:
            yield """idle"""
        else:
            yield """loading…"""
        yield """</span>
      </button>
    </div>
    <div class=\"mpy-repl-body\">
      <div class=\"mpy-repl-term\" id=\"mpy-repl-term\" tabindex=\"-1\">
        """
        for e in d.repl_engines:
            yield """        <div
          class=\"mpy-repl-out\"
          data-engine-out=\""""
            yield str(e.id)
            yield """\"
          aria-live=\"polite\"
          """
            if e.id != d.repl_default_engine:
                yield """hidden"""
            yield """        ></div>
        """
        yield """        <div class=\"mpy-repl-line\">
          <span class=\"mpy-repl-prompt\" aria-hidden=\"true\">&gt;&gt;&gt; </span>
          <label class=\"visually-hidden\" for=\"mpy-repl-in\">Python input</label>
          <input id=\"mpy-repl-in\" type=\"text\" autocomplete=\"off\" spellcheck=\"false\" />
        </div>
      </div>
    </div>
  </div>
  <script>
  (() => """
        yield """{
    const el = document.getElementById(\"mpy-repl\");
    if (!el) return;
    const prefix = (el.dataset.basePath || \"\").split(\"/\").join(\"\");
    const p = window.location.pathname;
    const pathPref = (p === \"/cdn\" || p.startsWith(\"/cdn/\")) ? \"/cdn\" : \"\";
    el.dataset.cdnBase = window.location.origin + (prefix || pathPref || \"\");
  })();
  </script>
  <script src=\""""
        yield str(d.repl_js_src)
        yield """\" defer></script>
  """
    yield """
  <script>
  (() => """
    yield """{
    const nav = document.getElementById(\"pkg-nav\");
    if (!nav) return;
    const active = nav.dataset.active || \"\";
    const filterInput = document.getElementById(\"pkg-nav-filter\");
    const filterEmpty = document.getElementById(\"pkg-nav-filter-empty\");

    function setOpen(li, open) """
    yield """{
      const btn = li.querySelector(\":scope > .tree-row > .tree-toggle\")
        || li.querySelector(\":scope > .tree-toggle\");
      const kids = li.querySelector(\":scope > .tree-children\");
      li.classList.toggle(\"is-open\", open);
      if (btn) btn.setAttribute(\"aria-expanded\", open ? \"true\" : \"false\");
      if (kids) kids.hidden = !open;
    }

    function openAncestors(leaf) """
    yield """{
      let el = leaf;
      while (el && el !== nav) """
    yield """{
        if (el.classList && el.classList.contains(\"is-folder\")) setOpen(el, true);
        el = el.parentElement;
      }
    }

    if (active) """
    yield """{
      const leaf = nav.querySelector(`.tree-node[data-package=\"$"""
    yield """{CSS.escape(active)}\"]`);
      if (leaf) openAncestors(leaf);
    }

    nav.addEventListener(\"click\", (ev) => """
    yield """{
      const btn = ev.target.closest(\".tree-toggle\");
      if (!btn || !nav.contains(btn)) return;
      const li = btn.closest(\".tree-node\");
      if (!li) return;
      setOpen(li, !li.classList.contains(\"is-open\"));
    });

    nav.addEventListener(\"change\", (ev) => """
    yield """{
      const sel = ev.target.closest(\".tree-ver-select\");
      if (!sel) return;
      const opt = sel.selectedOptions[0];
      const href = opt && opt.dataset.href;
      if (href) window.location.href = href;
    });

    function applyFilter(raw) """
    yield """{
      const q = String(raw || \"\").trim().toLowerCase();
      const nodes = nav.querySelectorAll(\".tree-node\");
      if (!q) """
    yield """{
        nodes.forEach((li) => """
    yield """{
          li.hidden = false;
          if (li.classList.contains(\"is-folder\")) setOpen(li, false);
        });
        if (filterEmpty) filterEmpty.hidden = true;
        if (active) """
    yield """{
          const leaf = nav.querySelector(`.tree-node[data-package=\"$"""
    yield """{CSS.escape(active)}\"]`);
          if (leaf) openAncestors(leaf);
        }
        return;
      }

      nodes.forEach((li) => """
    yield """{ li.hidden = true; });
      let hits = 0;
      nav.querySelectorAll(\".tree-node[data-package]\").forEach((leaf) => """
    yield """{
        const hay = leaf.dataset.search || leaf.dataset.package || \"\";
        if (!hay.includes(q)) return;
        hits += 1;
        leaf.hidden = false;
        openAncestors(leaf);
        let p = leaf.parentElement;
        while (p && p !== nav) """
    yield """{
          if (p.classList && p.classList.contains(\"tree-node\")) p.hidden = false;
          p = p.parentElement;
        }
      });
      nav.querySelectorAll(\".tree-node.is-folder\").forEach((folder) => """
    yield """{
        const hay = folder.dataset.search || folder.dataset.name || \"\";
        if (!hay.includes(q)) return;
        hits += 1;
        folder.hidden = false;
        setOpen(folder, true);
        folder.querySelectorAll(\".tree-node\").forEach((n) => """
    yield """{ n.hidden = false; });
        let p = folder.parentElement;
        while (p && p !== nav) """
    yield """{
          if (p.classList && p.classList.contains(\"tree-node\")) """
    yield """{
            p.hidden = false;
            if (p.classList.contains(\"is-folder\")) setOpen(p, true);
          }
          p = p.parentElement;
        }
      });
      if (filterEmpty) filterEmpty.hidden = hits > 0;
    }

    if (filterInput) """
    yield """{
      filterInput.addEventListener(\"input\", () => applyFilter(filterInput.value));
      filterInput.addEventListener(\"keydown\", (ev) => """
    yield """{
        if (ev.key === \"Escape\") """
    yield """{
          filterInput.value = \"\";
          applyFilter(\"\");
          filterInput.blur();
        }
      });
    }
  })();
  </script>
  """
    if d.current_user:
        yield """  <script>
  (function () """
        yield """{
    const btn = document.getElementById(\"nav-logout\");
    if (!btn) return;
    const apiBase = \""""
        yield str(d.base_path)
        yield """\";
    btn.addEventListener(\"click\", async () => """
        yield """{
      const headers = """
        yield """{ \"Content-Type\": \"application/json\" };
      try """
        yield """{
        const csrfRes = await fetch(apiBase + \"/auth/csrf\", """
        yield """{ credentials: \"same-origin\" });
        if (csrfRes.ok) """
        yield """{
          const data = await csrfRes.json();
          if (data.csrf_token) headers[\"X-CSRF-Token\"] = data.csrf_token;
        }
      } catch (_) """
        yield """{}
      await fetch(apiBase + \"/auth/logout\", """
        yield """{
        method: \"POST\",
        credentials: \"same-origin\",
        headers,
      });
      window.location.href = apiBase + \"/channels/lead\";
    });
  })();
  </script>
  """
    yield """  <script type=\"module\" src=\""""
    yield str(d.inspect_js)
    yield """\"></script>
</body>
</html>
"""
