#!/usr/bin/env bash
# Idempotent operator secrets for public-test / local docker.
#
# Writes (never commits):
#   .secrets/cdn.env   — METAL_CDN_BOOTSTRAP_ADMIN_EMAIL + PASSWORD
#   .secrets/token     — created later by scripts/dev-up.sh (API key)
#
# If .secrets/cdn.env already exists with a valid email, leave it alone
# (DB user would drift). Reserved-TLD emails (.local / .test / …) are
# rewritten in place — pydantic EmailStr rejects them at Settings load.
#
#   ./scripts/ensure-secrets.sh
#   METAL_CDN_BOOTSTRAP_ADMIN_EMAIL=ops@example.com ./scripts/ensure-secrets.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SECRETS="$ROOT/.secrets"
ENV_FILE="$SECRETS/cdn.env"
# email-validator rejects RFC 6761 special-use TLDs (.local, .test, …).
DEFAULT_EMAIL="demo@cdn.pymergetic.com"

_email_ok() {
  local e="$1"
  python3 - "$e" <<'PY'
import sys
try:
    from email_validator import validate_email, EmailNotValidError
except ImportError:
    # No validator in PATH — accept anything with one @ and a dotted domain.
    e = sys.argv[1]
    sys.exit(0 if ("@" in e and "." in e.rsplit("@", 1)[-1] and not e.lower().endswith((".local", ".test", ".invalid", ".localhost"))) else 1)
try:
    validate_email(sys.argv[1], check_deliverability=False)
except EmailNotValidError:
    sys.exit(1)
sys.exit(0)
PY
}

_write_env() {
  local email="$1" pass="$2"
  umask 077
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/ensure-secrets.sh — do not commit.
METAL_CDN_BOOTSTRAP_ADMIN_EMAIL=$email
METAL_CDN_BOOTSTRAP_ADMIN_PASSWORD=$pass
EOF
  chmod 600 "$ENV_FILE"
}

mkdir -p "$SECRETS"
chmod 700 "$SECRETS" 2>/dev/null || true

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  set -a
  # shellcheck disable=SC1091
  source "$ENV_FILE"
  set +a
  CUR_EMAIL="${METAL_CDN_BOOTSTRAP_ADMIN_EMAIL:-}"
  CUR_PASS="${METAL_CDN_BOOTSTRAP_ADMIN_PASSWORD:-}"
  if [[ -n "$CUR_EMAIL" && -n "$CUR_PASS" ]] && _email_ok "$CUR_EMAIL"; then
    echo "OK  $ENV_FILE already present (not rotating)"
    echo "    login email: $CUR_EMAIL"
    exit 0
  fi
  # Migrate reserved-TLD / empty email; keep password if present.
  NEW_EMAIL="${METAL_CDN_BOOTSTRAP_ADMIN_EMAIL:-$DEFAULT_EMAIL}"
  if ! _email_ok "$NEW_EMAIL"; then
    NEW_EMAIL="$DEFAULT_EMAIL"
  fi
  if [[ -z "$CUR_PASS" ]]; then
    echo "FAIL: $ENV_FILE has no METAL_CDN_BOOTSTRAP_ADMIN_PASSWORD — delete it and re-run" >&2
    exit 1
  fi
  _write_env "$NEW_EMAIL" "$CUR_PASS"
  echo "OK  repaired $ENV_FILE (email was invalid for EmailStr)"
  echo "    login email: $NEW_EMAIL"
  echo "    note: if a DB user already exists under the old address, delete .data or re-bootstrap"
  exit 0
fi

EMAIL="${METAL_CDN_BOOTSTRAP_ADMIN_EMAIL:-$DEFAULT_EMAIL}"
if ! _email_ok "$EMAIL"; then
  echo "FAIL: METAL_CDN_BOOTSTRAP_ADMIN_EMAIL=$EMAIL is not a valid EmailStr (no .local/.test/…)" >&2
  exit 1
fi
PASS="${METAL_CDN_BOOTSTRAP_ADMIN_PASSWORD:-}"
if [[ -z "$PASS" ]]; then
  PASS="$(openssl rand -base64 24 2>/dev/null | tr -d '/+=' | head -c 32)"
  if [[ ${#PASS} -lt 16 ]]; then
    PASS="$(head -c 24 /dev/urandom | xxd -p -c 24)"
  fi
fi

_write_env "$EMAIL" "$PASS"

echo "OK  wrote $ENV_FILE"
echo "    login email: $EMAIL"
echo "    password:    (see file — chmod 600)"
