#!/usr/bin/env bash
# Copy shared Inspect contract (Py + www) from metalpython into this package
# so Docker / pip installs can `import pymergetic.metal.inspect` without a
# sibling checkout.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/pymergetic/metal/inspect"

find_metal() {
  local c
  for c in \
    "${METALPYTHON:-}/extmod/metal/src/pymergetic/metal/inspect" \
    "$ROOT/../metalpython/extmod/metal/src/pymergetic/metal/inspect" \
    "$ROOT/../../metalpython/extmod/metal/src/pymergetic/metal/inspect"; do
    if [[ -n "$c" && -f "$c/adapter_fastapi.py" ]]; then
      echo "$c"
      return 0
    fi
  done
  return 1
}

SRC="$(find_metal)" || {
  echo "FAIL: metal inspect not found (set METALPYTHON=… or sibling ../metalpython)" >&2
  exit 1
}

echo "==> sync metal inspect → $DEST"
rm -rf "$DEST"
mkdir -p "$DEST"
# Python contract only (skip C / __pycache__).
for f in __init__.py app.py adapter_fastapi.py adapter_microdot.py \
  api.py shells.py dispatch.py self_desc.py stubs.py; do
  cp -f "$SRC/$f" "$DEST/$f"
done
mkdir -p "$DEST/www"
cp -a "$SRC/www/inspect" "$DEST/www/inspect"
cat >"$DEST/README.md" <<'EOF'
# pymergetic.metal.inspect (synced)

Generated by `scripts/sync-metal-inspect.sh` from metalpython
`extmod/metal/src/pymergetic/metal/inspect`. Do not edit here — edit the
metalpython source and re-sync before `docker build` / `dev-up`.
EOF
echo "OK → $DEST ($(find "$DEST" -type f | wc -l) files)"
